// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Telartes.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Telartes.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        internal static string CulturalAgenda {
            get {
                return ResourceManager.GetString("CulturalAgenda", resourceCulture);
            }
        }
        
        internal static string Calls {
            get {
                return ResourceManager.GetString("Calls", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_Title {
            get {
                return ResourceManager.GetString("Connection_Msg_Title", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_No_Connection {
            get {
                return ResourceManager.GetString("Connection_Msg_No_Connection", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_Confirm_Connection {
            get {
                return ResourceManager.GetString("Connection_Msg_Confirm_Connection", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_No_Server_Connection {
            get {
                return ResourceManager.GetString("Connection_Msg_No_Server_Connection", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_OK {
            get {
                return ResourceManager.GetString("Connection_Msg_OK", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_YES {
            get {
                return ResourceManager.GetString("Connection_Msg_YES", resourceCulture);
            }
        }
        
        internal static string Connection_Msg_NO {
            get {
                return ResourceManager.GetString("Connection_Msg_NO", resourceCulture);
            }
        }
    }
}
